import type { Metadata } from "next";
import { Inter, Newsreader } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

const newsreader = Newsreader({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Data Center Energy Monitor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={newsreader.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
